name: gnome-recipes
version: 2.0.4
summary: GNOME loves to cook
description: |
  Recipes is an easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

  Recipes comes with a collection of recipes that have been collected by GNOME contributors
  from all over the world. It also lets you store your own recipes and share them with your
  friends.

  The major features of Recipes include:
    * Add and edit your own recipes
    * Share recipes with your friends
    * Export and print shopping lists
    * Adjust quantities based on the number of servings
    * Mark recipes to cook later or add them to your favorites
    * Add notes to recipes
    * Hands-free cooking instruction mode

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  gnome-recipes:
    interface: dbus
    bus: session
    name: org.gnome.Recipes

apps:
  gnome-recipes:
    extensions: [ gnome-3-38 ]
    command: usr/bin/gnome-recipes
    plugs:
      - cups-control
      - avahi-observe
      - home
      - mount-observe
      - network
      - pulseaudio
      - screen-inhibit-control
      - unity7
    desktop: usr/share/applications/org.gnome.Recipes.desktop

parts:
  gnome-recipes:
    source: https://gitlab.gnome.org/GNOME/recipes.git
    source-type: git
    source-tag: 2.0.4
    override-build: |
      sed -i.bak -e 's|=org.gnome.Recipes$|=${SNAP}/meta/gui/org.gnome.Recipes.png|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Recipes.desktop.in
      sed -i.bak -e 's|\])$|\], symlink_media: false)|g' $SNAPCRAFT_PART_SRC/help/meson.build
      sed -i.bak -e 's|DATADIR|"/snap/gnome-recipes/current/usr/share"|g' $SNAPCRAFT_PART_SRC/src/gr-appdata.c
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/512x512/org.gnome.Recipes.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/gnome-recipes/current/usr/share/applications/org.gnome.Recipes.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-recipes/current/usr, -Dautoar=yes]
    organize:
      snap/gnome-recipes/current/usr: usr
    stage-packages:
      - iso-codes
      - libgnome-autoar-0-0
      - libgoa-1.0-0b
      - libsoup-gnome2.4-1
      - gir1.2-soup-2.4
      - libarchive13
  libraries:
    plugin: nil
    build-packages:
      - libgoa-1.0-dev
      - libgnome-autoar-0-dev
